import type { RouteLocationNormalized, RouteRecordRaw } from 'vue-router'

export const PERMISSIONS = {
  DashboardView: 'Dashboard.View',

  PatientsView: 'Patients.View',
  AppointmentsView: 'Appointments.View',
  OpdCheckupsView: 'OPD.Checkups.View',

  HrDepartmentsView: 'HR.Departments.View',
  HrDesignationsView: 'HR.Designations.View',
  HrWorkforceView: 'HR.Workforce.View',
  HrShiftsView: 'HR.Shifts.View',
  HrLeaveTypesView: 'HR.LeaveTypes.View',
  HrPermissionsView: 'HR.Permissions.View',
  HrOnboardingChecklistItemsView: 'HR.OnboardingChecklistItems.View',
  HrAttendanceLogsView: 'HR.AttendanceLogs.View',
  HrDutyRostersView: 'HR.DutyRosters.View',
  HrLeaveBalancesView: 'HR.LeaveBalances.View',
  HrLeaveRequestsView: 'HR.LeaveRequests.View',
  HrPayrollsView: 'HR.Payrolls.View',
  HrCredentialsView: 'HR.Credentials.View',
  HrTrainingEnrollmentsView: 'HR.TrainingEnrollments.View',
  HrPerformanceAppraisalsView: 'HR.PerformanceAppraisals.View',
  HrDisciplinaryIncidentsView: 'HR.DisciplinaryIncidents.View',
  HrEmploymentProfileTagsView: 'HR.EmploymentProfileTags.View',

  FinancePaymentsView: 'Finance.Payments.View',
  FinanceCounterClosingView: 'Finance.CounterClosing.View',
  FinanceCoaView: 'Finance.COA.View',
  FinanceExpenseVouchersView: 'Finance.ExpenseVouchers.View',
  FinanceDailyClosingView: 'Finance.DailyClosing.View',
  FinancePaymentCategoriesView: 'Finance.PaymentCategories.View',
  FinanceRefundsView: 'Finance.Refunds.View',
  FinanceClaimsView: 'Finance.Claims.View',
  FinanceSehatCardClaimsView: 'Finance.SehatCardClaims.View',
  FinancePanelBillingView: 'Finance.PanelBilling.View',
  FinancePostingView: 'Finance.Posting.View',
  FinanceDoctorShareView: 'Finance.DoctorShare.View',
  FinanceLeakageView: 'Finance.Leakage.View',

  AdminCompanyInfoView: 'Admin.CompanyInfo.View',
  AdminUsersView: 'Admin.Users.View',
  AdminPermissionsView: 'Admin.Permissions.View',
  AdminJobRolesView: 'Admin.JobRoles.View',
  AuditLogsView: 'Audit.Logs.View',
  ObservabilityAdminView: 'Observability.Admin.View',

  LabTestsView: 'Lab.Tests.View',
  LabCategoriesView: 'Lab.Categories.View',
  LabSampleCollectionView: 'Lab.SampleCollection.View',
  LabResultsView: 'Lab.Results.View',
  LabOrdersView: 'Lab.Orders.View',
  LabReportsView: 'Lab.Reports.View',
  LabApprovalsView: 'Lab.Approvals.View',
  RadiologyWorklistView: 'Radiology.Worklist.View',
  RadiologyReportingView: 'Radiology.Reporting.View',

  PharmacyMedicinesView: 'Pharmacy.Medicines.View',
  PharmacyCategoriesView: 'Pharmacy.Categories.View',
  PharmacyStockView: 'Pharmacy.Stock.View',
  PharmacyIssueView: 'Pharmacy.Issue.View',
  PharmacyDispensingView: 'Pharmacy.Dispensing.View',
  PharmacyBatchesView: 'Pharmacy.Batches.View',
  PharmacySalesView: 'Pharmacy.Sales.View',
  PharmacyFreeMedicineView: 'Pharmacy.FreeMedicine.View',
  PharmacyPaymentModesView: 'Pharmacy.PaymentModes.View',
  PharmacyReportsView: 'Pharmacy.Reports.View',

  IpdAdmissionsView: 'IPD.Admissions.View',
  IpdBedBoardView: 'IPD.BedBoard.View',
  IpdNursingView: 'IPD.Nursing.View',
  IpdMarView: 'IPD.MAR.View',
  IpdDischargeView: 'IPD.Discharge.View',
  EmergencyErView: 'Emergency.ER.View',
  MlcLegalRegisterView: 'Emergency.MLC.View',
  OtSurgeryView: 'Operations.Surgery.View',
  MaternityView: 'Maternity.View',
  RegulatoryReportsView: 'Regulatory.Reports.View',
  WelfareDeskView: 'Welfare.Desk.View',
  PatientFacilitationView: 'PatientFacilitation.View',
  FbrEinvoicingView: 'FBR.EInvoicing.View',
  ProvincialTaxView: 'Tax.Provincial.View',
  AiAgentMarketplaceView: 'AI.AgentMarketplace.View',
  IntegrationHubView: 'IntegrationHub.View',
  DowntimeModeView: 'Downtime.Mode.View',
  DocumentManagementView: 'Documents.Management.View',
  BiometricCnicView: 'Identity.BiometricCNIC.View',
  MultiBranchControlsView: 'Enterprise.MultiBranch.View',
  PaymentGatewayView: 'Payments.Gateway.View',
  AiGovernanceView: 'AI.Governance.View',

  InventoryProcurementView: 'Inventory.Procurement.View',
  InventoryStockMovementsView: 'Inventory.StockMovements.View',
  InventoryReportsView: 'Inventory.Reports.View',

  AnalyticsExecutiveView: 'Analytics.Executive.View',
  AnalyticsClinicalView: 'Analytics.Clinical.View',
  AnalyticsFinanceView: 'Analytics.Finance.View',

  InteroperabilityOutboxView: 'Interoperability.Outbox.View',
  InteroperabilityFhirView: 'Interoperability.FHIR.View',
  InteroperabilityPartnersView: 'Interoperability.Partners.View',

  QualityView: 'Quality.View',
  QualityIncidentsManage: 'Quality.Incidents.Manage',
  QualityAuditsManage: 'Quality.Audits.Manage',
  QualityComplianceManage: 'Quality.Compliance.Manage',
  QualityActionsManage: 'Quality.Actions.Manage',
  QualityRisksManage: 'Quality.Risks.Manage',
  QualityInfectionControlManage: 'Quality.InfectionControl.Manage',
  QualityMortalityReviewsManage: 'Quality.MortalityReviews.Manage',
  QualityReportsView: 'Quality.Reports.View',

  BloodBankManage: 'BloodBank.Manage',
  AdvancedClinicalAiScribeView: 'AdvancedClinical.AiScribe.View',
  TelemedicineWorkspaceView: 'Telemedicine.Workspace.View',
  PacsViewerView: 'Radiology.PacsViewer.View',
  AbdmAbhaView: 'Interoperability.ABDMABHA.View',
  LisEnterpriseView: 'LIS.Enterprise.View',

  ReportsPatientView: 'Reports.Patient.View',
  ReportsFinanceView: 'Reports.Finance.View',
  ReportsLabView: 'Reports.Lab.View',
} as const

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]
export type PermissionInput = PermissionCode | (string & {})
export type PermissionRule = readonly PermissionInput[]

export const PERMISSION_BACKEND_SYNC_GROUPS: Record<string, PermissionCode[]> = {
  Pharmacy: [
    PERMISSIONS.PharmacyMedicinesView,
    PERMISSIONS.PharmacyCategoriesView,
    PERMISSIONS.PharmacyStockView,
    PERMISSIONS.PharmacyIssueView,
    PERMISSIONS.PharmacyDispensingView,
    PERMISSIONS.PharmacyBatchesView,
    PERMISSIONS.PharmacySalesView,
    PERMISSIONS.PharmacyFreeMedicineView,
    PERMISSIONS.PharmacyPaymentModesView,
    PERMISSIONS.PharmacyReportsView,
  ],
  IPD: [
    PERMISSIONS.IpdAdmissionsView,
    PERMISSIONS.IpdBedBoardView,
    PERMISSIONS.IpdNursingView,
    PERMISSIONS.IpdMarView,
    PERMISSIONS.IpdDischargeView,
  ],
  Inventory: [
    PERMISSIONS.InventoryProcurementView,
    PERMISSIONS.InventoryStockMovementsView,
    PERMISSIONS.InventoryReportsView,
  ],
  Analytics: [
    PERMISSIONS.AnalyticsExecutiveView,
    PERMISSIONS.AnalyticsClinicalView,
    PERMISSIONS.AnalyticsFinanceView,
  ],
  Interoperability: [
    PERMISSIONS.InteroperabilityOutboxView,
    PERMISSIONS.InteroperabilityFhirView,
    PERMISSIONS.InteroperabilityPartnersView,
  ],
  Radiology: [
    PERMISSIONS.RadiologyWorklistView,
    PERMISSIONS.RadiologyReportingView,
  ],
  Quality: [
    PERMISSIONS.QualityView,
    PERMISSIONS.QualityIncidentsManage,
    PERMISSIONS.QualityAuditsManage,
    PERMISSIONS.QualityComplianceManage,
    PERMISSIONS.QualityActionsManage,
    PERMISSIONS.QualityRisksManage,
    PERMISSIONS.QualityInfectionControlManage,
    PERMISSIONS.QualityMortalityReviewsManage,
    PERMISSIONS.QualityReportsView,
  ],
  BloodBank: [PERMISSIONS.BloodBankManage],
  PakistanMarket: [
    PERMISSIONS.FinanceSehatCardClaimsView,
    PERMISSIONS.FinancePanelBillingView,
    PERMISSIONS.EmergencyErView,
    PERMISSIONS.MlcLegalRegisterView,
    PERMISSIONS.OtSurgeryView,
    PERMISSIONS.MaternityView,
    PERMISSIONS.RegulatoryReportsView,
    PERMISSIONS.WelfareDeskView,
    PERMISSIONS.PatientFacilitationView,
  ],
  IntegrationAutomation: [
    PERMISSIONS.FbrEinvoicingView,
    PERMISSIONS.ProvincialTaxView,
    PERMISSIONS.AiAgentMarketplaceView,
    PERMISSIONS.IntegrationHubView,
    PERMISSIONS.DowntimeModeView,
    PERMISSIONS.DocumentManagementView,
    PERMISSIONS.BiometricCnicView,
    PERMISSIONS.MultiBranchControlsView,
    PERMISSIONS.PaymentGatewayView,
    PERMISSIONS.AiGovernanceView,
  ],
  AdvancedHms: [
    PERMISSIONS.AdvancedClinicalAiScribeView,
    PERMISSIONS.TelemedicineWorkspaceView,
    PERMISSIONS.PacsViewerView,
    PERMISSIONS.AbdmAbhaView,
  ],
  EnterpriseLIS: [PERMISSIONS.LisEnterpriseView],
}

export const FRONTEND_PERMISSION_CODES = Object.values(PERMISSIONS)

const routePermissionByPath: Record<string, PermissionRule> = {
  '/dashboard': [PERMISSIONS.DashboardView],

  '/patients': [PERMISSIONS.PatientsView],
  '/patients/queue': [PERMISSIONS.PatientsView],
  '/patients/:id': [PERMISSIONS.PatientsView],
  '/checkups': [PERMISSIONS.OpdCheckupsView],
  '/opd/workflow': [PERMISSIONS.OpdCheckupsView],
  '/opd/prescriptions': [PERMISSIONS.OpdCheckupsView],
  '/opd/diagnosis': [PERMISSIONS.OpdCheckupsView],
  '/opd/vital-signs': [PERMISSIONS.OpdCheckupsView],
  '/opd/procedures': [PERMISSIONS.OpdCheckupsView],
  '/opd/follow-ups': [PERMISSIONS.OpdCheckupsView],
  '/appointments': [PERMISSIONS.AppointmentsView],
  '/appointments/calendar': [PERMISSIONS.AppointmentsView],

  '/hr/departments': [PERMISSIONS.HrDepartmentsView],
  '/hr/designations': [PERMISSIONS.HrDesignationsView],
  '/employees': [PERMISSIONS.HrWorkforceView],
  '/employees/:id': [PERMISSIONS.HrWorkforceView],
  '/hr/shifts': [PERMISSIONS.HrShiftsView],
  '/hr/leave-types': [PERMISSIONS.HrLeaveTypesView],
  '/hr/permissions': [PERMISSIONS.HrPermissionsView],
  '/hr/onboarding-checklist-items': [PERMISSIONS.HrOnboardingChecklistItemsView],
  '/hr/attendance-logs': [PERMISSIONS.HrAttendanceLogsView],
  '/hr/duty-rosters': [PERMISSIONS.HrDutyRostersView],
  '/hr/leave-balances': [PERMISSIONS.HrLeaveBalancesView],
  '/hr/leave-requests': [PERMISSIONS.HrLeaveRequestsView],
  '/hr/payrolls': [PERMISSIONS.HrPayrollsView],
  '/hr/credentials': [PERMISSIONS.HrCredentialsView],
  '/hr/training-enrollments': [PERMISSIONS.HrTrainingEnrollmentsView],
  '/hr/performance-appraisals': [PERMISSIONS.HrPerformanceAppraisalsView],
  '/hr/disciplinary-incidents': [PERMISSIONS.HrDisciplinaryIncidentsView],
  '/hr/employment-profile-tags': [PERMISSIONS.HrEmploymentProfileTagsView],

  '/payments': [PERMISSIONS.FinancePaymentsView],
  '/payments/new': [PERMISSIONS.FinancePaymentsView],
  '/payments/:id(\\d+)': [PERMISSIONS.FinancePaymentsView],
  '/payments/:id(\\d+)/print': [PERMISSIONS.FinancePaymentsView],
  '/payments/:id(\\d+)/thermal': [PERMISSIONS.FinancePaymentsView],
  '/finance/counter-closing': [PERMISSIONS.FinanceCounterClosingView],
  '/finance/chartofaccounts': [PERMISSIONS.FinanceCoaView],
  '/finance/expense-vouchers': [PERMISSIONS.FinanceExpenseVouchersView],
  '/finance/daily-closing': [PERMISSIONS.FinanceDailyClosingView],
  '/finance/revenue-vouchers': [PERMISSIONS.FinancePostingView],
  '/finance/refunds': [PERMISSIONS.FinanceRefundsView],
  '/finance/claims': [PERMISSIONS.FinanceClaimsView],
  '/finance/sehat-card-claims': [PERMISSIONS.FinanceSehatCardClaimsView],
  '/finance/panel-billing': [PERMISSIONS.FinancePanelBillingView],
  '/finance/posting-dashboard': [PERMISSIONS.FinancePostingView],
  '/finance/doctor-share': [PERMISSIONS.FinanceDoctorShareView],
  '/finance/leakage-dashboard': [PERMISSIONS.FinanceLeakageView],
  '/admin/payment-categories': [PERMISSIONS.FinancePaymentCategoriesView],

  '/company-info': [PERMISSIONS.AdminCompanyInfoView],
  '/admin/users': [PERMISSIONS.AdminUsersView],
  '/admin/audit': [PERMISSIONS.AuditLogsView],
  '/admin/observability': [PERMISSIONS.ObservabilityAdminView],
  '/admin/permission-sync': [PERMISSIONS.AdminPermissionsView],

  '/pharmacy/dispensing': [PERMISSIONS.PharmacyDispensingView],
  '/pharmacy/batches': [PERMISSIONS.PharmacyBatchesView],
  '/pharmacy/unit-box-sales': [PERMISSIONS.PharmacySalesView],
  '/pharmacy/free-medicine': [PERMISSIONS.PharmacyFreeMedicineView],
  '/pharmacy/payment-modes': [PERMISSIONS.PharmacyPaymentModesView],
  '/pharmacy/reports': [PERMISSIONS.PharmacyReportsView],

  '/diagnostics/orders': [PERMISSIONS.LabOrdersView],
  '/diagnostics/lab-tests': [PERMISSIONS.LabTestsView],
  '/diagnostics/categories': [PERMISSIONS.LabCategoriesView],
  '/diagnostics/sample-collection': [PERMISSIONS.LabSampleCollectionView],
  '/diagnostics/results': [PERMISSIONS.LabResultsView],
  '/diagnostics/reports': [PERMISSIONS.LabReportsView],
  '/diagnostics/approvals': [PERMISSIONS.LabApprovalsView],
  '/radiology/worklist': [PERMISSIONS.RadiologyWorklistView],
  '/radiology/reporting': [PERMISSIONS.RadiologyReportingView],

  '/ipd/admissions': [PERMISSIONS.IpdAdmissionsView],
  '/ipd/bed-board': [PERMISSIONS.IpdBedBoardView],
  '/ipd/nursing': [PERMISSIONS.IpdNursingView],
  '/ipd/mar': [PERMISSIONS.IpdMarView],
  '/ipd/discharge': [PERMISSIONS.IpdDischargeView],
  '/emergency/triage': [PERMISSIONS.IpdAdmissionsView],
  '/emergency/encounters': [PERMISSIONS.IpdAdmissionsView],
  '/emergency/observation-beds': [PERMISSIONS.IpdBedBoardView],
  '/emergency/er-workflow': [PERMISSIONS.EmergencyErView],
  '/emergency/mlc-register': [PERMISSIONS.MlcLegalRegisterView],
  '/ot/procedures': [PERMISSIONS.IpdNursingView],
  '/ot/surgery-management': [PERMISSIONS.OtSurgeryView],
  '/icu/workflows': [PERMISSIONS.IpdNursingView],
  '/maternity/labor-room': [PERMISSIONS.MaternityView],
  '/regulatory/government-reports': [PERMISSIONS.RegulatoryReportsView],
  '/welfare/charity-zakat': [PERMISSIONS.WelfareDeskView],
  '/patient-facilitation/complaints': [PERMISSIONS.PatientFacilitationView],
  '/integrations/hub': [PERMISSIONS.IntegrationHubView],
  '/integrations/fbr-e-invoicing': [PERMISSIONS.FbrEinvoicingView],
  '/integrations/provincial-tax': [PERMISSIONS.ProvincialTaxView],
  '/ai/agent-marketplace': [PERMISSIONS.AiAgentMarketplaceView],
  '/ai/governance': [PERMISSIONS.AiGovernanceView],
  '/downtime/offline-queue': [PERMISSIONS.DowntimeModeView],
  '/documents/management': [PERMISSIONS.DocumentManagementView],
  '/identity/biometric-cnic': [PERMISSIONS.BiometricCnicView],
  '/enterprise/multi-branch': [PERMISSIONS.MultiBranchControlsView],
  '/payments/gateways': [PERMISSIONS.PaymentGatewayView],

  '/inventory/procurement': [PERMISSIONS.InventoryProcurementView],
  '/inventory/suppliers': [PERMISSIONS.InventoryProcurementView],
  '/inventory/requisitions': [PERMISSIONS.InventoryProcurementView],
  '/inventory/purchase-orders': [PERMISSIONS.InventoryProcurementView],
  '/inventory/receiving': [PERMISSIONS.InventoryProcurementView],
  '/inventory/stock-lots': [PERMISSIONS.InventoryStockMovementsView],
  '/inventory/expiry': [PERMISSIONS.InventoryStockMovementsView],
  '/inventory/adjustments': [PERMISSIONS.InventoryStockMovementsView],
  '/inventory/stock-movements': [PERMISSIONS.InventoryStockMovementsView],
  '/inventory/reports': [PERMISSIONS.InventoryReportsView],

  '/analytics/executive': [PERMISSIONS.AnalyticsExecutiveView],
  '/analytics/clinical': [PERMISSIONS.AnalyticsClinicalView],
  '/analytics/finance': [PERMISSIONS.AnalyticsFinanceView],
  '/analytics/exports': [PERMISSIONS.AnalyticsFinanceView],

  '/patient-engagement/portal-accounts': [PERMISSIONS.PatientsView],
  '/patient-engagement/prescription-access': [PERMISSIONS.PatientsView],
  '/patient-engagement/notifications': [PERMISSIONS.PatientsView],
  '/patient-engagement/consents': [PERMISSIONS.PatientsView],
  '/patient-engagement/messages': [PERMISSIONS.PatientsView],

  '/interoperability/outbox': [PERMISSIONS.InteroperabilityOutboxView],
  '/interoperability/hl7-fhir': [PERMISSIONS.InteroperabilityFhirView],
  '/interoperability/partners': [PERMISSIONS.InteroperabilityPartnersView],
  '/interoperability/exchange': [PERMISSIONS.InteroperabilityFhirView],
  '/interoperability/webhooks': [PERMISSIONS.InteroperabilityFhirView],
  '/interoperability/pacs-dicom': [PERMISSIONS.InteroperabilityFhirView],

  '/quality/incidents': [PERMISSIONS.QualityIncidentsManage],
  '/quality/incident-actions': [PERMISSIONS.QualityIncidentsManage],
  '/quality/audit-checklists': [PERMISSIONS.QualityAuditsManage],
  '/quality/audit-findings': [PERMISSIONS.QualityAuditsManage],
  '/quality/compliance-tasks': [PERMISSIONS.QualityComplianceManage],
  '/quality/corrective-actions': [PERMISSIONS.QualityActionsManage],
  '/quality/risk-register': [PERMISSIONS.QualityRisksManage],
  '/quality/infection-control': [PERMISSIONS.QualityInfectionControlManage],
  '/quality/mortality-reviews': [PERMISSIONS.QualityMortalityReviewsManage],
  '/quality/reports': [PERMISSIONS.QualityReportsView],

  '/blood-bank/donors': [PERMISSIONS.BloodBankManage],
  '/blood-bank/blood-units': [PERMISSIONS.BloodBankManage],
  '/blood-bank/cross-matching': [PERMISSIONS.BloodBankManage],
  '/blood-bank/issue-return': [PERMISSIONS.BloodBankManage],
  '/blood-bank/cold-chain': [PERMISSIONS.BloodBankManage],
  '/clinical/ai-voice-scribe': [PERMISSIONS.AdvancedClinicalAiScribeView],
  '/telemedicine/workspace': [PERMISSIONS.TelemedicineWorkspaceView],
  '/radiology/pacs-viewer': [PERMISSIONS.PacsViewerView],
  '/interoperability/abdm-abha': [PERMISSIONS.AbdmAbhaView],
  '/lis/outreach-orders': [PERMISSIONS.LisEnterpriseView],
  '/lis/phlebotomy-collections': [PERMISSIONS.LisEnterpriseView],
  '/lis/accessioning-barcoding': [PERMISSIONS.LisEnterpriseView],
  '/lis/specimen-routing': [PERMISSIONS.LisEnterpriseView],
  '/lis/instrument-worklists': [PERMISSIONS.LisEnterpriseView],
  '/lis/anatomic-pathology': [PERMISSIONS.LisEnterpriseView],
  '/lis/molecular-diagnostics': [PERMISSIONS.LisEnterpriseView],
  '/lis/microbiology': [PERMISSIONS.LisEnterpriseView],
  '/lis/auto-verification': [PERMISSIONS.LisEnterpriseView],
  '/lis/reflex-testing': [PERMISSIONS.LisEnterpriseView],
  '/lis/critical-alerts': [PERMISSIONS.LisEnterpriseView],
  '/lis/reagent-inventory': [PERMISSIONS.LisEnterpriseView],
  '/lis/biobanking': [PERMISSIONS.LisEnterpriseView],
  '/lis/document-control': [PERMISSIONS.LisEnterpriseView],
  '/lis/predictive-maintenance': [PERMISSIONS.LisEnterpriseView],
  '/lis/ai-interpretation': [PERMISSIONS.LisEnterpriseView],
}

const firstAllowedRoutePriority: Array<{ permission: PermissionInput; path: string }> = [
  { permission: PERMISSIONS.DashboardView, path: '/dashboard' },
  { permission: PERMISSIONS.PatientsView, path: '/patients' },
  { permission: PERMISSIONS.OpdCheckupsView, path: '/checkups' },
  { permission: PERMISSIONS.AppointmentsView, path: '/appointments' },
  { permission: PERMISSIONS.HrDepartmentsView, path: '/hr/departments' },
  { permission: PERMISSIONS.HrDesignationsView, path: '/hr/designations' },
  { permission: PERMISSIONS.HrWorkforceView, path: '/employees' },
  { permission: PERMISSIONS.FinancePaymentsView, path: '/payments' },
  { permission: PERMISSIONS.FinanceCounterClosingView, path: '/finance/counter-closing' },
  { permission: PERMISSIONS.FinanceCoaView, path: '/finance/chartofaccounts' },
  { permission: PERMISSIONS.FinanceExpenseVouchersView, path: '/finance/expense-vouchers' },
  { permission: PERMISSIONS.FinanceDailyClosingView, path: '/finance/daily-closing' },
  { permission: PERMISSIONS.FinanceSehatCardClaimsView, path: '/finance/sehat-card-claims' },
  { permission: PERMISSIONS.EmergencyErView, path: '/emergency/er-workflow' },
  { permission: PERMISSIONS.MaternityView, path: '/maternity/labor-room' },
  { permission: PERMISSIONS.IntegrationHubView, path: '/integrations/hub' },
  { permission: PERMISSIONS.FbrEinvoicingView, path: '/integrations/fbr-e-invoicing' },
  { permission: PERMISSIONS.AiAgentMarketplaceView, path: '/ai/agent-marketplace' },
  { permission: PERMISSIONS.AdminCompanyInfoView, path: '/company-info' },
  { permission: PERMISSIONS.AdminUsersView, path: '/admin/users' },
  { permission: PERMISSIONS.AuditLogsView, path: '/admin/audit' },
  { permission: PERMISSIONS.ObservabilityAdminView, path: '/admin/observability' },
  { permission: PERMISSIONS.FinancePaymentCategoriesView, path: '/admin/payment-categories' },
  { permission: PERMISSIONS.PharmacyDispensingView, path: '/pharmacy/dispensing' },
  { permission: PERMISSIONS.LabOrdersView, path: '/diagnostics/orders' },
  { permission: PERMISSIONS.LabTestsView, path: '/diagnostics/lab-tests' },
  { permission: PERMISSIONS.LabCategoriesView, path: '/diagnostics/categories' },
  { permission: PERMISSIONS.IpdAdmissionsView, path: '/ipd/admissions' },
  { permission: PERMISSIONS.InventoryProcurementView, path: '/inventory/procurement' },
  { permission: PERMISSIONS.AnalyticsExecutiveView, path: '/analytics/executive' },
  { permission: PERMISSIONS.InteroperabilityOutboxView, path: '/interoperability/outbox' },
  { permission: PERMISSIONS.QualityIncidentsManage, path: '/quality/incidents' },
  { permission: PERMISSIONS.BloodBankManage, path: '/blood-bank/donors' },
  { permission: PERMISSIONS.LisEnterpriseView, path: '/lis/outreach-orders' },
]

const menuPermissionRules: Record<string, PermissionRule> = {
  dashboard: [PERMISSIONS.DashboardView],

  patients: [
    PERMISSIONS.PatientsView,
    PERMISSIONS.OpdCheckupsView,
    PERMISSIONS.AppointmentsView,
    PERMISSIONS.FinancePaymentsView,
    PERMISSIONS.FinanceCounterClosingView,
  ],
  'patients.list': [PERMISSIONS.PatientsView],
  'patients.queue': [PERMISSIONS.PatientsView],
  'patients.checkups': [PERMISSIONS.OpdCheckupsView],
  'patients.appointments': [PERMISSIONS.AppointmentsView],
  'patients.payments': [PERMISSIONS.FinancePaymentsView],
  'patients.counterClosing': [PERMISSIONS.FinanceCounterClosingView],

  opd: [PERMISSIONS.OpdCheckupsView],
  'opd.workflow': [PERMISSIONS.OpdCheckupsView],
  'opd.prescriptions': [PERMISSIONS.OpdCheckupsView],
  'opd.diagnosis': [PERMISSIONS.OpdCheckupsView],
  'opd.vitals': [PERMISSIONS.OpdCheckupsView],
  'opd.procedures': [PERMISSIONS.OpdCheckupsView],
  'opd.followups': [PERMISSIONS.OpdCheckupsView],

  hr: [
    PERMISSIONS.HrDepartmentsView,
    PERMISSIONS.HrDesignationsView,
    PERMISSIONS.HrWorkforceView,
    PERMISSIONS.HrShiftsView,
    PERMISSIONS.HrLeaveTypesView,
    PERMISSIONS.HrPermissionsView,
    PERMISSIONS.HrOnboardingChecklistItemsView,
    PERMISSIONS.HrAttendanceLogsView,
    PERMISSIONS.HrDutyRostersView,
    PERMISSIONS.HrLeaveBalancesView,
    PERMISSIONS.HrLeaveRequestsView,
    PERMISSIONS.HrPayrollsView,
    PERMISSIONS.HrCredentialsView,
    PERMISSIONS.HrTrainingEnrollmentsView,
    PERMISSIONS.HrPerformanceAppraisalsView,
    PERMISSIONS.HrDisciplinaryIncidentsView,
    PERMISSIONS.HrEmploymentProfileTagsView,
  ],
  'hr.departments': [PERMISSIONS.HrDepartmentsView],
  'hr.designations': [PERMISSIONS.HrDesignationsView],
  'hr.workforce': [PERMISSIONS.HrWorkforceView],
  'hr.shifts': [PERMISSIONS.HrShiftsView],
  'hr.leaveTypes': [PERMISSIONS.HrLeaveTypesView],
  'hr.permissions': [PERMISSIONS.HrPermissionsView],
  'hr.onboardingChecklistItems': [PERMISSIONS.HrOnboardingChecklistItemsView],
  'hr.attendanceLogs': [PERMISSIONS.HrAttendanceLogsView],
  'hr.dutyRosters': [PERMISSIONS.HrDutyRostersView],
  'hr.leaveBalances': [PERMISSIONS.HrLeaveBalancesView],
  'hr.leaveRequests': [PERMISSIONS.HrLeaveRequestsView],
  'hr.payrolls': [PERMISSIONS.HrPayrollsView],
  'hr.credentials': [PERMISSIONS.HrCredentialsView],
  'hr.trainingEnrollments': [PERMISSIONS.HrTrainingEnrollmentsView],
  'hr.performanceAppraisals': [PERMISSIONS.HrPerformanceAppraisalsView],
  'hr.disciplinaryIncidents': [PERMISSIONS.HrDisciplinaryIncidentsView],
  'hr.employmentProfileTags': [PERMISSIONS.HrEmploymentProfileTagsView],

  finance: [
    PERMISSIONS.FinancePaymentsView,
    PERMISSIONS.FinanceCounterClosingView,
    PERMISSIONS.FinanceCoaView,
    PERMISSIONS.FinanceExpenseVouchersView,
    PERMISSIONS.FinanceDailyClosingView,
    PERMISSIONS.FinancePaymentCategoriesView,
    PERMISSIONS.FinanceRefundsView,
    PERMISSIONS.FinanceClaimsView,
    PERMISSIONS.FinanceSehatCardClaimsView,
    PERMISSIONS.FinancePanelBillingView,
    PERMISSIONS.FinancePostingView,
    PERMISSIONS.FinanceDoctorShareView,
    PERMISSIONS.FinanceLeakageView,
  ],
  'finance.receipts': [PERMISSIONS.FinancePaymentsView],
  'finance.refunds': [PERMISSIONS.FinanceRefundsView],
  'finance.claims': [PERMISSIONS.FinanceClaimsView],
  'finance.sehatCardClaims': [PERMISSIONS.FinanceSehatCardClaimsView],
  'finance.panelBilling': [PERMISSIONS.FinancePanelBillingView],
  'finance.posting': [PERMISSIONS.FinancePostingView],
  'finance.doctorShare': [PERMISSIONS.FinanceDoctorShareView],
  'finance.leakage': [PERMISSIONS.FinanceLeakageView],
  'finance.coa': [PERMISSIONS.FinanceCoaView],
  'finance.expenseVouchers': [PERMISSIONS.FinanceExpenseVouchersView],
  'finance.dailyClosing': [PERMISSIONS.FinanceDailyClosingView],

  lab: [
    PERMISSIONS.LabTestsView,
    PERMISSIONS.LabCategoriesView,
    PERMISSIONS.LabSampleCollectionView,
    PERMISSIONS.LabResultsView,
    PERMISSIONS.LabOrdersView,
    PERMISSIONS.LabReportsView,
    PERMISSIONS.LabApprovalsView,
    PERMISSIONS.RadiologyWorklistView,
    PERMISSIONS.RadiologyReportingView,
  ],
  'lab.orders': [PERMISSIONS.LabOrdersView],
  'lab.tests': [PERMISSIONS.LabTestsView],
  'lab.categories': [PERMISSIONS.LabCategoriesView],
  'lab.sample': [PERMISSIONS.LabSampleCollectionView],
  'lab.results': [PERMISSIONS.LabResultsView],
  'lab.reports': [PERMISSIONS.LabReportsView],
  'lab.approvals': [PERMISSIONS.LabApprovalsView],
  'radiology.worklist': [PERMISSIONS.RadiologyWorklistView],
  'radiology.reporting': [PERMISSIONS.RadiologyReportingView],

  pharmacy: [
    PERMISSIONS.PharmacyMedicinesView,
    PERMISSIONS.PharmacyCategoriesView,
    PERMISSIONS.PharmacyStockView,
    PERMISSIONS.PharmacyIssueView,
    PERMISSIONS.PharmacyDispensingView,
    PERMISSIONS.PharmacyBatchesView,
    PERMISSIONS.PharmacySalesView,
    PERMISSIONS.PharmacyFreeMedicineView,
    PERMISSIONS.PharmacyPaymentModesView,
    PERMISSIONS.PharmacyReportsView,
  ],
  'pharmacy.dispensing': [PERMISSIONS.PharmacyDispensingView],
  'pharmacy.batches': [PERMISSIONS.PharmacyBatchesView],
  'pharmacy.sales': [PERMISSIONS.PharmacySalesView],
  'pharmacy.freeMedicine': [PERMISSIONS.PharmacyFreeMedicineView],
  'pharmacy.paymentModes': [PERMISSIONS.PharmacyPaymentModesView],
  'pharmacy.reports': [PERMISSIONS.PharmacyReportsView],
  'pharmacy.medicines': [PERMISSIONS.PharmacyMedicinesView],
  'pharmacy.categories': [PERMISSIONS.PharmacyCategoriesView],
  'pharmacy.stock': [PERMISSIONS.PharmacyStockView],
  'pharmacy.issue': [PERMISSIONS.PharmacyIssueView],

  ipd: [
    PERMISSIONS.IpdAdmissionsView,
    PERMISSIONS.IpdBedBoardView,
    PERMISSIONS.IpdNursingView,
    PERMISSIONS.IpdMarView,
    PERMISSIONS.IpdDischargeView,
  ],
  'ipd.admissions': [PERMISSIONS.IpdAdmissionsView],
  'ipd.bedBoard': [PERMISSIONS.IpdBedBoardView],
  'ipd.nursing': [PERMISSIONS.IpdNursingView],
  'ipd.mar': [PERMISSIONS.IpdMarView],
  'ipd.discharge': [PERMISSIONS.IpdDischargeView],

  pakistanMarket: [
    PERMISSIONS.FinanceSehatCardClaimsView,
    PERMISSIONS.FinancePanelBillingView,
    PERMISSIONS.EmergencyErView,
    PERMISSIONS.MlcLegalRegisterView,
    PERMISSIONS.OtSurgeryView,
    PERMISSIONS.MaternityView,
    PERMISSIONS.RegulatoryReportsView,
    PERMISSIONS.WelfareDeskView,
    PERMISSIONS.PatientFacilitationView,
  ],
  'pakistanMarket.sehatCard': [PERMISSIONS.FinanceSehatCardClaimsView],
  'pakistanMarket.panelBilling': [PERMISSIONS.FinancePanelBillingView],
  'pakistanMarket.er': [PERMISSIONS.EmergencyErView],
  'pakistanMarket.mlc': [PERMISSIONS.MlcLegalRegisterView],
  'pakistanMarket.otSurgery': [PERMISSIONS.OtSurgeryView],
  'pakistanMarket.maternity': [PERMISSIONS.MaternityView],
  'pakistanMarket.regulatory': [PERMISSIONS.RegulatoryReportsView],
  'pakistanMarket.welfare': [PERMISSIONS.WelfareDeskView],
  'pakistanMarket.complaints': [PERMISSIONS.PatientFacilitationView],

  integrationAutomation: [
    PERMISSIONS.IntegrationHubView,
    PERMISSIONS.FbrEinvoicingView,
    PERMISSIONS.ProvincialTaxView,
    PERMISSIONS.AiAgentMarketplaceView,
    PERMISSIONS.AiGovernanceView,
    PERMISSIONS.DowntimeModeView,
    PERMISSIONS.DocumentManagementView,
    PERMISSIONS.BiometricCnicView,
    PERMISSIONS.MultiBranchControlsView,
    PERMISSIONS.PaymentGatewayView,
  ],
  'integrationAutomation.hub': [PERMISSIONS.IntegrationHubView],
  'integrationAutomation.fbr': [PERMISSIONS.FbrEinvoicingView],
  'integrationAutomation.provincialTax': [PERMISSIONS.ProvincialTaxView],
  'integrationAutomation.aiMarketplace': [PERMISSIONS.AiAgentMarketplaceView],
  'integrationAutomation.aiGovernance': [PERMISSIONS.AiGovernanceView],
  'integrationAutomation.downtime': [PERMISSIONS.DowntimeModeView],
  'integrationAutomation.documents': [PERMISSIONS.DocumentManagementView],
  'integrationAutomation.biometric': [PERMISSIONS.BiometricCnicView],
  'integrationAutomation.multiBranch': [PERMISSIONS.MultiBranchControlsView],
  'integrationAutomation.paymentGateways': [PERMISSIONS.PaymentGatewayView],

  inventory: [
    PERMISSIONS.InventoryProcurementView,
    PERMISSIONS.InventoryStockMovementsView,
    PERMISSIONS.InventoryReportsView,
  ],
  'inventory.procurement': [PERMISSIONS.InventoryProcurementView],
  'inventory.stockMovements': [PERMISSIONS.InventoryStockMovementsView],
  'inventory.reports': [PERMISSIONS.InventoryReportsView],

  analytics: [
    PERMISSIONS.AnalyticsExecutiveView,
    PERMISSIONS.AnalyticsClinicalView,
    PERMISSIONS.AnalyticsFinanceView,
  ],
  'analytics.executive': [PERMISSIONS.AnalyticsExecutiveView],
  'analytics.clinical': [PERMISSIONS.AnalyticsClinicalView],
  'analytics.finance': [PERMISSIONS.AnalyticsFinanceView],

  patientEngagement: [PERMISSIONS.PatientsView],
  'patientEngagement.portal': [PERMISSIONS.PatientsView],
  'patientEngagement.prescriptions': [PERMISSIONS.PatientsView],
  'patientEngagement.notifications': [PERMISSIONS.PatientsView],
  'patientEngagement.consents': [PERMISSIONS.PatientsView],
  'patientEngagement.messages': [PERMISSIONS.PatientsView],

  interoperability: [
    PERMISSIONS.InteroperabilityOutboxView,
    PERMISSIONS.InteroperabilityFhirView,
    PERMISSIONS.InteroperabilityPartnersView,
  ],
  'interoperability.outbox': [PERMISSIONS.InteroperabilityOutboxView],
  'interoperability.fhir': [PERMISSIONS.InteroperabilityFhirView],
  'interoperability.partners': [PERMISSIONS.InteroperabilityPartnersView],

  quality: [
    PERMISSIONS.QualityIncidentsManage,
    PERMISSIONS.QualityAuditsManage,
    PERMISSIONS.QualityComplianceManage,
    PERMISSIONS.QualityActionsManage,
    PERMISSIONS.QualityRisksManage,
    PERMISSIONS.QualityInfectionControlManage,
    PERMISSIONS.QualityMortalityReviewsManage,
    PERMISSIONS.QualityReportsView,
  ],
  'quality.incidents': [PERMISSIONS.QualityIncidentsManage],
  'quality.incidentActions': [PERMISSIONS.QualityIncidentsManage],
  'quality.auditChecklists': [PERMISSIONS.QualityAuditsManage],
  'quality.auditFindings': [PERMISSIONS.QualityAuditsManage],
  'quality.complianceTasks': [PERMISSIONS.QualityComplianceManage],
  'quality.correctiveActions': [PERMISSIONS.QualityActionsManage],
  'quality.riskRegister': [PERMISSIONS.QualityRisksManage],
  'quality.infectionControl': [PERMISSIONS.QualityInfectionControlManage],
  'quality.mortalityReviews': [PERMISSIONS.QualityMortalityReviewsManage],
  'quality.reports': [PERMISSIONS.QualityReportsView],

  bloodBank: [PERMISSIONS.BloodBankManage],
  'bloodBank.donors': [PERMISSIONS.BloodBankManage],
  'bloodBank.units': [PERMISSIONS.BloodBankManage],
  'bloodBank.crossMatching': [PERMISSIONS.BloodBankManage],
  'bloodBank.issueReturn': [PERMISSIONS.BloodBankManage],
  'bloodBank.coldChain': [PERMISSIONS.BloodBankManage],

  advancedHms: [
    PERMISSIONS.AdvancedClinicalAiScribeView,
    PERMISSIONS.TelemedicineWorkspaceView,
    PERMISSIONS.PacsViewerView,
    PERMISSIONS.AbdmAbhaView,
  ],
  'advancedHms.aiScribe': [PERMISSIONS.AdvancedClinicalAiScribeView],
  'advancedHms.telemedicine': [PERMISSIONS.TelemedicineWorkspaceView],
  'advancedHms.pacsViewer': [PERMISSIONS.PacsViewerView],
  'advancedHms.abdmAbha': [PERMISSIONS.AbdmAbhaView],

  enterpriseLis: [PERMISSIONS.LisEnterpriseView],
  'enterpriseLis.outreach': [PERMISSIONS.LisEnterpriseView],
  'enterpriseLis.phlebotomy': [PERMISSIONS.LisEnterpriseView],
  'enterpriseLis.accessioning': [PERMISSIONS.LisEnterpriseView],
  'enterpriseLis.routing': [PERMISSIONS.LisEnterpriseView],
  'enterpriseLis.instruments': [PERMISSIONS.LisEnterpriseView],
  'enterpriseLis.pathology': [PERMISSIONS.LisEnterpriseView],
  'enterpriseLis.molecular': [PERMISSIONS.LisEnterpriseView],
  'enterpriseLis.microbiology': [PERMISSIONS.LisEnterpriseView],
  'enterpriseLis.verification': [PERMISSIONS.LisEnterpriseView],
  'enterpriseLis.reflex': [PERMISSIONS.LisEnterpriseView],
  'enterpriseLis.alerts': [PERMISSIONS.LisEnterpriseView],
  'enterpriseLis.reagents': [PERMISSIONS.LisEnterpriseView],
  'enterpriseLis.biobanking': [PERMISSIONS.LisEnterpriseView],
  'enterpriseLis.documents': [PERMISSIONS.LisEnterpriseView],
  'enterpriseLis.maintenance': [PERMISSIONS.LisEnterpriseView],
  'enterpriseLis.aiInterpretation': [PERMISSIONS.LisEnterpriseView],

  reports: [
    PERMISSIONS.ReportsPatientView,
    PERMISSIONS.ReportsFinanceView,
    PERMISSIONS.ReportsLabView,
  ],
  'reports.patient': [PERMISSIONS.ReportsPatientView],
  'reports.finance': [PERMISSIONS.ReportsFinanceView],
  'reports.lab': [PERMISSIONS.ReportsLabView],

  admin: [
    PERMISSIONS.AdminCompanyInfoView,
    PERMISSIONS.AdminUsersView,
    PERMISSIONS.AdminPermissionsView,
    PERMISSIONS.AdminJobRolesView,
    PERMISSIONS.FinancePaymentCategoriesView,
    PERMISSIONS.AuditLogsView,
    PERMISSIONS.ObservabilityAdminView,
  ],
  'admin.company': [PERMISSIONS.AdminCompanyInfoView],
  'admin.paymentCategories': [PERMISSIONS.FinancePaymentCategoriesView],
  'admin.users': [PERMISSIONS.AdminUsersView],
  'admin.roles': [PERMISSIONS.AdminPermissionsView, PERMISSIONS.AdminJobRolesView],
  'admin.permissionSync': [PERMISSIONS.AdminPermissionsView],
  'admin.audit': [PERMISSIONS.AuditLogsView],
  'admin.observability': [PERMISSIONS.ObservabilityAdminView],
}

export const hasPermission = (permissions: readonly string[], permission: PermissionInput): boolean =>
  permissions.includes(permission)

export const hasAnyPermission = (
  permissions: readonly string[],
  required: PermissionRule = [],
): boolean => required.length === 0 || required.some((permission) => hasPermission(permissions, permission))

export const hasAllPermissions = (
  permissions: readonly string[],
  required: PermissionRule = [],
): boolean => required.every((permission) => hasPermission(permissions, permission))

export const canSeeMenuItem = (key: string, permissions: readonly string[]): boolean => {
  const required = menuPermissionRules[key]
  return required ? hasAnyPermission(permissions, required) : false
}

export const getFirstAllowedRoute = (permissions: readonly string[]): string => {
  const match = firstAllowedRoutePriority.find((route) =>
    hasPermission(permissions, route.permission),
  )
  return match?.path ?? '/forbidden'
}

export const applyRoutePermissionMeta = <T extends RouteRecordRaw[]>(routes: T): T => {
  for (const route of routes) {
    const permissions = routePermissionByPath[route.path]

    if (permissions?.length) {
      route.meta = {
        ...(route.meta ?? {}),
        requiresAuth: true,
        permissions: [...permissions],
      }
    }

    if (route.children) {
      applyRoutePermissionMeta(route.children)
    }
  }

  return routes
}

export const getRequiredRoutePermissions = (to: RouteLocationNormalized): string[] =>
  to.matched.flatMap((route) => route.meta.permissions ?? [])

export const canAccessRoute = (
  to: RouteLocationNormalized,
  permissions: readonly string[],
): boolean => hasAllPermissions(permissions, getRequiredRoutePermissions(to))
